name: Validation

on:
  push:
    branches:
      - main
      - patch/**
    path:
      - onecode/**
      - tests/**

  pull_request:
    branches:
      - main

jobs:
  formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Formatting
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install isort

      - name: Check Formatting
        run: |
          flake8 onecode tests/unit/ --exclude=__init__.py,tests/data --max-line-length=100
          isort . -m3 --thirdparty . --check-only --skip tests/data --skip examples/

  testing:
    name: Check Testing
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Python libraries
        run: |
          python -m pip install --upgrade pip
          pip install .[developer]

      - name: Check Testing
        run: |
          python -m pytest tests -n auto
